#!/usr/bin/env bash
# PostgreSQL 17 as a permanent service on the production host.
#
# Settings come from research/08-postgres-selfhosted.md section 3.2, the CX23
# profile, with two deliberate departures recorded there and here:
#
#   * archive_mode is OFF. The researched config turns it on with an
#     archive_command that shells out to pgBackRest. pgBackRest is not
#     installed yet (off-site backups are deferred), and archive_mode = on
#     with a failing archive_command does not degrade gracefully: Postgres
#     retains every WAL segment it cannot archive until the disk fills.
#     Turn this on in the same change that installs pgBackRest, not before.
#
#   * The data directory is a bind mount to an explicit host path, never a
#     named or anonymous volume, for the reason given in the research: an
#     anonymous volume is silently replaced when the container is recreated,
#     which is the commonest way a Dockerised Postgres is lost.
#
# Two databases on one instance:
#   foundit      — production. Empty until Phase 9 deploys.
#   foundit_dev  — development, reached from the laptop over an SSH tunnel.
#
# ---------------------------------------------------------------------------
# THE BOOTSTRAP ROLE IS `postgres` AND THE OWNER IS NOT A SUPERUSER, AND THAT
# IS THE PHASE 9a REVIEW'S F8.
#
# This file used to start the container with `POSTGRES_USER: foundit_owner`.
# The official PostgreSQL image creates `POSTGRES_USER` as the **initdb
# superuser**, and PostgreSQL will not let SUPERUSER be taken away from the
# role initdb bootstrapped with. So on the host `foundit_owner` WAS the
# superuser, permanently — which is the Phase 8 review's F1 met a second time,
# the thing `.github/workflows/ci.yml` explains at length and uses
# `POSTGRES_USER: postgres` to avoid, and a stop condition
# `docs/launch-runbook.md` step 3a would have hit on its first run:
#
#     SEE: `f|f` on every row. If `foundit_owner` shows `t`, stop.
#
# A superuser owner bypasses every row-level security policy in the schema, so
# every SECURITY DEFINER function behaves differently from the way it behaves
# in CI, in development, and in every test this repository has.
#
# THIS IS A DATA-DIRECTORY DECISION AND CANNOT BE UNDONE IN PLACE. `initdb`
# runs once, on an empty ./data, and the role it creates is a superuser for
# ever. So a host that already ran the old version of this file has to be
# re-initialised, which is `docs/launch-runbook.md` step 1f — safe only while
# `foundit` is empty, which that step makes the operator confirm with a row
# count before anything is deleted.
#
# THE ROLE STATEMENTS BELOW ARE THE THIRD COPY OF ONE ARRANGEMENT.
# `db/dev-roles.sql` is the first and `.github/workflows/ci.yml` the second,
# and tests/deploy.test.mjs asserts the three agree about the clauses that
# matter: NOSUPERUSER, NOBYPASSRLS, CREATEROLE, the three `with inherit false,
# admin option` grants, and `grant set on parameter "foundit.definer"`. They
# cannot be one file, because this one has to inject passwords that exist only
# on this machine and the other two use fixed development ones.
set -euo pipefail

IMAGE="pgvector/pgvector:pg17-trixie"
BASE=/srv/foundit
SECRETS=/root/.foundit

sudo mkdir -p "$BASE"/{data,conf} "$SECRETS"
sudo chmod 700 "$SECRETS"

# --- The passwords are generated here and never leave the machine -----------
#
# Three roles, three passwords, all generated by openssl on this box and
# written to a 0600 file owned by root. None of them has ever been typed into
# a chat window, an editor, or a file git can see.
#
#   POSTGRES_PASSWORD      the `postgres` BOOTSTRAP SUPERUSER. It creates the
#                          roles, hands the schemas to the owner and creates
#                          the `vector` extension — the three things a
#                          non-superuser cannot do — and nothing else on this
#                          machine ever uses it. Not the app, not the
#                          migrations, not the backups.
#   FOUNDIT_OWNER_PASSWORD foundit_owner. Migrations only, and NOSUPERUSER
#                          NOBYPASSRLS since 13 September 2026 (F8).
#   FOUNDIT_APP_PASSWORD   foundit_app. The web application and the eval.
#   FOUNDIT_EMBED_PASSWORD foundit_embed. scripts/embed.mjs and nothing else —
#                          see db/migrations/0005_embed_role.sql for why it is
#                          a separate role rather than a job the app runs.
#   FOUNDIT_AUTH_PASSWORD  foundit_auth. Better Auth and nothing else — the
#                          five tables in auth_core, and no object in any other
#                          schema. db/migrations/0013_accounts.sql says why.
#
# A file that already exists is left alone, and a file that predates one of
# these roles gets the one new line appended rather than being regenerated:
# rewriting it would change the owner's password under a running database.
if [ ! -f "$SECRETS/db.env" ]; then
  SUPER_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
  OWNER_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
  APP_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
  EMBED_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
  AUTH_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
  printf 'POSTGRES_PASSWORD=%s\nFOUNDIT_OWNER_PASSWORD=%s\nFOUNDIT_APP_PASSWORD=%s\nFOUNDIT_EMBED_PASSWORD=%s\nFOUNDIT_AUTH_PASSWORD=%s\n' \
    "$SUPER_PW" "$OWNER_PW" "$APP_PW" "$EMBED_PW" "$AUTH_PW" \
    | sudo tee "$SECRETS/db.env" >/dev/null
  sudo chmod 600 "$SECRETS/db.env"
  echo "Generated new credentials in $SECRETS/db.env (root only, 0600)."
else
  # FOUNDIT_OWNER_PASSWORD is new as of F8: before it, POSTGRES_PASSWORD WAS
  # the owner's, because the owner was the bootstrap superuser. A db.env that
  # predates the change gets the one line appended rather than being
  # regenerated — rewriting it would change the superuser's password under a
  # running database.
  if ! sudo grep -q '^FOUNDIT_OWNER_PASSWORD=' "$SECRETS/db.env"; then
    OWNER_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
    printf 'FOUNDIT_OWNER_PASSWORD=%s\n' "$OWNER_PW" \
      | sudo tee -a "$SECRETS/db.env" >/dev/null
    echo "Added FOUNDIT_OWNER_PASSWORD to $SECRETS/db.env."
  fi
  if ! sudo grep -q '^FOUNDIT_EMBED_PASSWORD=' "$SECRETS/db.env"; then
    EMBED_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
    printf 'FOUNDIT_EMBED_PASSWORD=%s\n' "$EMBED_PW" \
      | sudo tee -a "$SECRETS/db.env" >/dev/null
    echo "Added FOUNDIT_EMBED_PASSWORD to $SECRETS/db.env."
  fi
  if ! sudo grep -q '^FOUNDIT_AUTH_PASSWORD=' "$SECRETS/db.env"; then
    AUTH_PW=$(openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32)
    printf 'FOUNDIT_AUTH_PASSWORD=%s\n' "$AUTH_PW" \
      | sudo tee -a "$SECRETS/db.env" >/dev/null
    echo "Added FOUNDIT_AUTH_PASSWORD to $SECRETS/db.env."
  fi
  echo "Keeping the existing credentials in $SECRETS/db.env."
fi

# --- postgresql.conf --------------------------------------------------------
sudo tee "$BASE/conf/postgresql.conf" >/dev/null <<'CONF'
# Foundit — PostgreSQL 17 — Hetzner CX23 (2 vCPU / 4 GB / 40 GB NVMe)
# Shares the host with the app and a reverse proxy.
# See research/08-postgres-selfhosted.md section 3.2. Do not tune by feel.

# ---------- Connections ----------
listen_addresses = '*'                  # safe only because 5432 is bound to 127.0.0.1
port = 5432
max_connections = 30
superuser_reserved_connections = 3
tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 6

# ---------- Memory ----------
shared_buffers = 512MB
effective_cache_size = 1536MB
work_mem = 8MB
hash_mem_multiplier = 2.0
maintenance_work_mem = 128MB
autovacuum_work_mem = 64MB
temp_buffers = 8MB
huge_pages = try

# ---------- Planner / CPU ----------
random_page_cost = 1.1
seq_page_cost = 1.0
effective_io_concurrency = 200
maintenance_io_concurrency = 200
cpu_tuple_cost = 0.01
max_worker_processes = 4
max_parallel_workers = 2
max_parallel_workers_per_gather = 0
max_parallel_maintenance_workers = 1
jit = off

# ---------- WAL / checkpoints ----------
wal_level = replica
archive_mode = off                      # ON only when pgBackRest exists. See the header.
wal_compression = zstd
wal_buffers = 16MB
max_wal_size = 2GB
min_wal_size = 256MB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
synchronous_commit = on
full_page_writes = on
summarize_wal = off

# ---------- Autovacuum ----------
autovacuum = on
autovacuum_max_workers = 2
autovacuum_naptime = 30s
autovacuum_vacuum_threshold = 50
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_threshold = 50
autovacuum_analyze_scale_factor = 0.02
autovacuum_vacuum_cost_delay = 2ms
autovacuum_vacuum_cost_limit = 1000
autovacuum_freeze_max_age = 200000000

# ---------- Statistics / extensions ----------
shared_preload_libraries = 'pg_stat_statements'
compute_query_id = on
pg_stat_statements.max = 5000
pg_stat_statements.track = top
pg_stat_statements.track_utility = on
track_io_timing = on
track_activity_query_size = 4096
default_statistics_target = 100

# ---------- Safety valves ----------
statement_timeout = 0
idle_in_transaction_session_timeout = '5min'
lock_timeout = 0
deadlock_timeout = 1s

# ---------- Logging ----------
log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 500ms
log_min_messages = warning
log_checkpoints = on
log_lock_waits = on
log_autovacuum_min_duration = 0
log_temp_files = 0
log_connections = off
log_disconnections = off
log_line_prefix = '%m [%p] %q%u@%d %a '
log_timezone = 'UTC'
timezone = 'UTC'

# ---------- Security ----------
password_encryption = scram-sha-256
ssl = off
CONF

# --- compose ---------------------------------------------------------------
sudo tee "$BASE/docker-compose.yml" >/dev/null <<COMPOSE
name: foundit-db
services:
  db:
    image: ${IMAGE}
    container_name: foundit-dev-db
    restart: unless-stopped
    env_file: ${SECRETS}/db.env
    environment:
      # `postgres` AND NOT `foundit_owner`. The image creates POSTGRES_USER as
      # the initdb superuser and PostgreSQL will not let SUPERUSER be taken
      # away from it, so bootstrapping as the owner makes the owner a superuser
      # for the life of the data directory — and a superuser bypasses every
      # row-level security policy in the schema. The Phase 8 review's F1, the
      # Phase 9a review's F8, and the reason ci.yml says the same thing.
      POSTGRES_USER: postgres
      POSTGRES_DB: foundit
      # Deliberate: the image only applies this on first initialisation.
      POSTGRES_INITDB_ARGS: "--data-checksums"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ${BASE}/data:/var/lib/postgresql/data
      - ${BASE}/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      # 127.0.0.1 explicitly, belt and braces over the daemon-wide default.
      - "127.0.0.1:5432:5432"
    shm_size: 256mb
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d foundit"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 2g
COMPOSE

sudo docker compose -f "$BASE/docker-compose.yml" up -d
echo "Waiting for the database to accept connections..."
for i in $(seq 1 40); do
  if sudo docker exec foundit-dev-db pg_isready -U postgres -d foundit >/dev/null 2>&1; then
    echo "  ready after ${i}0s at most"; break
  fi
  sleep 3
done

sudo docker exec foundit-dev-db psql -v ON_ERROR_STOP=1 -U postgres -d foundit \
  -c "select 1" >/dev/null

# --- The OWNER, which is not a superuser -----------------------------------
#
# THE THIRD COPY OF `db/dev-roles.sql`, and the header says why it cannot be
# the same file: this one injects passwords that exist only on this machine.
# tests/deploy.test.mjs holds the three copies to the same clauses.
#
# Every statement here runs as the bootstrap superuser `postgres`, because
# every one of them is a thing a non-superuser cannot do — which is the whole
# argument for having a superuser that nothing else on the machine uses.
#
#   the three extensions   `vector` is not a trusted extension, so only a
#                          superuser can install it. 0001_init.sql's
#                          `create extension if not exists vector` then
#                          succeeds for the owner because it is already there
#                          and the statement returns before it checks a
#                          privilege.
#   the owner role         NOSUPERUSER NOBYPASSRLS, and CREATEROLE because
#                          0001, 0005 and 0013 create the application roles and
#                          0003 and 0013 run `alter role … set`.
#   the database owner     every schema, table, policy and function a migration
#                          creates has to belong to foundit_owner rather than
#                          to postgres: a SECURITY DEFINER function owned by a
#                          superuser is an authorisation bypass wearing a
#                          helpful hat.
#   the three memberships  `with inherit false` so the owner may SET ROLE and
#                          nothing more — with inherit, a policy scoped TO
#                          foundit_app would start applying to owner sessions,
#                          which is the opposite of what a non-superuser owner
#                          is for. `admin option` because 0003 and 0013 alter
#                          those roles' settings.
#   the parameter grant    0020 §2 attaches `SET "foundit.definer"` to twenty-
#                          odd definer functions, and writing a custom
#                          parameter into a catalogue entry needs either
#                          superuser or this grant.
echo "--- the owner role ---"
OWNER_PW_NOW=$(sudo grep '^FOUNDIT_OWNER_PASSWORD=' "$SECRETS/db.env" | cut -d= -f2-)
printf '%s\n' \
  "create extension if not exists citext;" \
  "create extension if not exists pg_trgm;" \
  "create extension if not exists vector;" \
  "do \$owner\$" \
  "begin" \
  "  if exists (select 1 from pg_roles where rolname = 'foundit_owner') then" \
  "    alter role foundit_owner login noinherit nosuperuser nobypassrls createrole password '${OWNER_PW_NOW}';" \
  "  else" \
  "    create role foundit_owner login noinherit nosuperuser nobypassrls createrole password '${OWNER_PW_NOW}';" \
  "  end if;" \
  "end" \
  "\$owner\$;" \
  "do \$own\$ begin execute format('alter database %I owner to foundit_owner', current_database()); end \$own\$;" \
  "alter schema public owner to foundit_owner;" \
  "grant set on parameter \"foundit.definer\" to foundit_owner;" \
  | sudo docker exec -i foundit-dev-db psql -v ON_ERROR_STOP=1 -qX \
      -U postgres -d foundit >/dev/null
unset OWNER_PW_NOW
echo "  foundit_owner owns the database and is NOT a superuser."

# --- The three non-owner roles, and their passwords -------------------------
#
# The migrations create foundit_app (0001), foundit_embed (0005) and
# foundit_auth (0013) with LOGIN and NO PASSWORD, because a migration is a
# tracked file that runs on this host and must never carry a credential. A role
# that cannot log in is the safe direction to fail in — but it also means
# nothing can connect as any of them until something outside the migrations
# sets a password, and that something is here.
#
# Until this existed, db.env carried FOUNDIT_APP_PASSWORD and nothing ever
# applied it, so the application role could not log in on the server at all.
#
# The passwords go in over STDIN rather than as arguments: an argument is
# visible in `ps` to every user on the box. They are generated above from
# openssl and stripped to alphanumerics, so a single-quoted SQL literal is safe
# without further escaping.
set_role_password() { # set_role_password <role> <password>
  printf "do \$\$\nbegin\n  if exists (select 1 from pg_roles where rolname = '%s') then\n    alter role %s login noinherit password '%s';\n  else\n    create role %s login noinherit password '%s';\n  end if;\nend\n\$\$;\n" \
    "$1" "$1" "$2" "$1" "$2" \
    | sudo docker exec -i foundit-dev-db psql -v ON_ERROR_STOP=1 -qX \
        -U postgres -d foundit >/dev/null
  echo "  $1 can log in."
}

APP_PW_NOW=$(sudo grep '^FOUNDIT_APP_PASSWORD=' "$SECRETS/db.env" | cut -d= -f2-)
EMBED_PW_NOW=$(sudo grep '^FOUNDIT_EMBED_PASSWORD=' "$SECRETS/db.env" | cut -d= -f2-)
AUTH_PW_NOW=$(sudo grep '^FOUNDIT_AUTH_PASSWORD=' "$SECRETS/db.env" | cut -d= -f2-)
echo "--- application roles ---"
set_role_password foundit_app "$APP_PW_NOW"
set_role_password foundit_embed "$EMBED_PW_NOW"
set_role_password foundit_auth "$AUTH_PW_NOW"
unset APP_PW_NOW EMBED_PW_NOW AUTH_PW_NOW

# And the owner's membership of each, which is what lets `db/test.sh` SET ROLE
# into an application role and watch it be refused. AFTER the three exist.
printf '%s\n' \
  "grant foundit_app   to foundit_owner with inherit false, admin option;" \
  "grant foundit_embed to foundit_owner with inherit false, admin option;" \
  "grant foundit_auth  to foundit_owner with inherit false, admin option;" \
  | sudo docker exec -i foundit-dev-db psql -v ON_ERROR_STOP=1 -qX \
      -U postgres -d foundit >/dev/null

# --- and the check the runbook's step 3a makes ------------------------------
#
# HERE RATHER THAN ONLY THERE. `docs/launch-runbook.md` step 3a reads this same
# table and says "if foundit_owner shows `t`, stop" — a stop condition the host
# as previously built would have hit on its first run (F8). Printing it at the
# end of the script that decides it means the answer is visible the moment it
# is decided rather than two steps later.
echo "--- no superuser but postgres, and nobody bypasses row-level security ---"
sudo docker exec foundit-dev-db psql -tAU postgres -d foundit -c \
  "select rolname || '|' || rolsuper || '|' || rolbypassrls from pg_roles
    where rolname not like 'pg\_%' order by rolname"

# The connection strings the laptop needs are assembled from db.env by hand and
# never written down here. To read one back:
#
#   ssh founditops@167.233.217.138 \
#     "sudo grep '^FOUNDIT_EMBED_PASSWORD=' /root/.foundit/db.env | cut -d= -f2"
#
# DATABASE_URL_EMBED is then
#   postgresql://foundit_embed:<that>@127.0.0.1:5433/foundit_dev
# through the tunnel, exactly as DATABASE_URL is for foundit_app.

# --- the development database ----------------------------------------------
if ! sudo docker exec foundit-dev-db psql -tAU postgres -d foundit \
      -c "select 1 from pg_database where datname='foundit_dev'" | grep -q 1; then
  sudo docker exec foundit-dev-db createdb -U postgres -O foundit_owner foundit_dev
  echo "Created foundit_dev."
fi

sudo docker exec foundit-dev-db psql -qAt -U postgres -d foundit \
  -c "create extension if not exists pg_stat_statements" >/dev/null

echo "--- versions ---"
sudo docker exec foundit-dev-db psql -tAU postgres -d foundit -c "select version()"
echo "--- settings that matter ---"
sudo docker exec foundit-dev-db psql -U postgres -d foundit -c \
  "select name, setting, unit from pg_settings where name in
   ('shared_buffers','work_mem','max_connections','jit','archive_mode',
    'wal_compression','autovacuum','password_encryption','data_checksums',
    'shared_preload_libraries') order by name"
echo "--- databases ---"
sudo docker exec foundit-dev-db psql -tAU postgres -d foundit -c "\l" | cut -d'|' -f1
echo "--- published ports (must be 127.0.0.1 only) ---"
sudo docker ps --filter name=foundit-dev-db --format '{{.Names}} {{.Ports}}'
sudo ss -ltnp 2>/dev/null | grep 5432 || true
