#!/usr/bin/env node
// ===========================================================================
// Start the built server, bound to this machine.
//
// `.next/standalone/server.js` is generated by Next and its first decision is
//
//     const hostname = process.env.HOSTNAME || '0.0.0.0'
//
// (node_modules/next/dist/build/utils.js). `0.0.0.0` is every interface the
// machine has, so `npm start` on a laptop in a café serves the application,
// its database-backed pages and its stack traces to everyone else on that
// wifi. Nothing in this repository asked for that; it was the default, and a
// default is not a decision.
//
// So the default is 127.0.0.1 — the loopback address, reachable from this
// machine and from nothing else — and it stays a default: HOSTNAME already set
// in the environment wins, which is how the container binds 0.0.0.0 behind the
// Cloudflare tunnel without anybody editing this file.
//
//   npm start                          -> http://127.0.0.1:3000
//   HOSTNAME=0.0.0.0 npm start         -> every interface, said out loud
//   PORT=4000 npm start                -> the port Next already reads
//
// Written as a Node script rather than `HOSTNAME=... node …` in package.json
// because that syntax is a shell feature, and npm runs scripts through cmd.exe
// on Windows, where it is a syntax error rather than an environment variable.
// ===========================================================================

import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { existsSync } from 'node:fs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SERVER = path.join(ROOT, '.next', 'standalone', 'server.js');

if (!existsSync(SERVER)) {
  process.stderr.write(
    [
      `ERROR: ${path.relative(ROOT, SERVER).split(path.sep).join('/')} does not exist.`,
      '',
      'Run `npm run build` first — it writes the standalone directory and then',
      'packages the browser assets into it (scripts/postbuild-standalone.mjs).',
      '',
    ].join('\n'),
  );
  process.exit(1);
}

// `??=` rather than `=`: an empty string is a deliberate value to Next (it
// falls back to 0.0.0.0), and only an unset variable is us choosing.
process.env.HOSTNAME ??= '127.0.0.1';

await import(pathToFileURL(SERVER).href);
